# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=2.6.0
maven_group=com.github.certifiedtater
archives_base_name=lifesteal
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.152.1+26.2
# https://maven.nucleoid.xyz/#/releases/eu/pb4/polymer-core
polymer_version=0.17.0+26.2-rc-2
# https://maven.nucleoid.xyz/#/releases/eu/pb4/sgui
sgui_version=2.1.0+26.2
server_translation_api_version=3.1.0+26.2
# https://modrinth.com/mod/unruled-api/versions
unruled_version=2.2+26.1
