# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.2
# Mod Properties
mod_version=2.6.0
maven_group=com.github.certifiedtater
archives_base_name=lifesteal
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.146.1+26.1.2
# https://maven.nucleoid.xyz/#/releases/eu/pb4/polymer-core
polymer_version=0.16.3+26.1.2
# https://maven.nucleoid.xyz/#/releases/eu/pb4/sgui
sgui_version=2.0.0-beta.2+26.1
server_translation_api_version=3.0.3+26.1
# https://modrinth.com/mod/unruled-api/versions
unruled_version=2.2+26.1
