# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
# Mod Properties
mod_version=2.6.3
maven_group=com.github.certifiedtater
archives_base_name=lifesteal
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.161.0+26.3
# https://maven.nucleoid.xyz/#/releases/eu/pb4/polymer-core
polymer_version=0.18.2+26.3
# https://maven.nucleoid.xyz/#/releases/eu/pb4/sgui
sgui_version=2.2.0+26.3
server_translation_api_version=3.2.0+26.3
# https://modrinth.com/mod/unruled-api/versions
unruled_version=2.3.3+26.2
